wifi:
  ssid: !secret ssid
  password: !secret wifi_password
  # Optional manual IP
  manual_ip:
    static_ip: $device_ip 
    gateway: 192.168.1.1
    subnet: 255.255.255.0

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret api_password

ota:
  password: !secret ota_password

text_sensor:
  - platform: version
    name: version
