substitutions:
  name: garage
  id_prefix: ${name}_
  label: Garage
  device_ip: 192.168.1.81

esphome:
  name: ${name}
  platform: ESP32
  board: nodemcu-32s
  includes:
  - _BLEDevice.h
  on_boot:
    priority: -800
    then:
    - lambda: |-
            BLEDevice::setPower(ESP_PWR_LVL_P9);

<<: !include .shared.yaml

esp32_ble_tracker:
  scan_interval: 30s

binary_sensor:
- id: open_sensor
  platform: template
  lambda: |-
    if(id(us_sensor).state < 0.2) {
      return true;
    }
    else { 
      return false;
    }

# Detect when the M3 bluetooth is on and within range
- id: m3
  platform: ble_presence
  mac_address: !secret m3_ble
  name: M3
  # Open the garage when the bluetooth signal is detected
  #  on_press:
  #  - cover.open: ${id_prefix}cover
  # Close the garage when the bluetooth signal is lost
  #  on_release:
  #  - delay: 30s
  #  - cover.close: ${id_prefix}cover

switch:
- platform: gpio
  pin: 15
  id: open_switch

sensor:
- id: us_sensor
  platform: ultrasonic
  trigger_pin: 12
  echo_pin: 13
  update_interval: 2s

- id: m3_rssi
  platform: ble_rssi
  mac_address: !secret m3_ble
  internal: true

cover:
- id: ${id_prefix}cover
  platform: template
  name: ${label}
  lambda: |-
    if(id(open_sensor).state) {
      return COVER_OPEN;
    }
    else { 
      return COVER_CLOSED;
    }
  open_action:
  - if:
      condition:
        binary_sensor.is_off: open_sensor
      then: 
      - switch.turn_on: open_switch
      - delay: 2s
      - switch.turn_off: open_switch
  close_action:
  - if:
      condition:
        binary_sensor.is_on: open_sensor
      then: 
      - switch.turn_on: open_switch
      - delay: 2s
      - switch.turn_off: open_switch
