esphome:
  name: garage
  platform: ESP8266
  board: nodemcu

wifi:
  ssid: "argyle"
  password: "C0lorBl0ck?"

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "g0rmley"

ota:
  password: "g0rmley"

switch:
- platform: gpio
  pin: 15
  name: “Garage Open Switch”
  internal: true
  id: garage_open_switch
  
binary_sensor:
- platform: gpio
  pin: 12
  name: “Garage Open Sensor”
  id: garage_open_sensor
  device_class: garage_door

cover:
- platform: template
  name: Garage
  lambda: |-
    if(id(garage_open_sensor).state) {
      return COVER_CLOSED;
    }
    else {
      return COVER_OPEN;
    }
  optimistic: true
  open_action:
  - switch.turn_on: garage_open_switch
  close_action:
  - switch.turn_off: garage_open_switch

  
