# Wireless controller for LiftMaster Gate Operator LA400
esphome:
  name: ${name}
  platform: ESP32
  board: nodemcu-32s
  includes:
  - _BLEDevice.h
  on_boot:
    priority: -800
    then:
    - lambda: |-
            BLEDevice::setPower(ESP_PWR_LVL_P9);

substitutions:
  name: gate
  id_prefix: ${name}_
  label: Gate
  device_ip: 192.168.1.82

<<: !include .shared.yaml

esp32_ble_tracker:
  scan_parameters:
    interval: 150ms
    window: 150ms

switch:
- id: ${id_prefix}open
  platform: gpio
  name: ${label} Open Switch
  pin: 
    number: 26
  
- id: ${id_prefix}sbc
  platform: gpio
  name: ${label} SBC Switch
  pin: 
    number: 25 
    inverted: true

- id: ${id_prefix}reset
  platform: gpio
  name: ${label} Reset Switch
  pin: 
    number: 33
    inverted: true
  
- id: ${id_prefix}stop
  platform: gpio
  name: ${label} Stop Switch
  pin: 32

binary_sensor:
# Detect when the Odyssey bluetooth is on and within range
- id: odyssey
  platform: ble_presence
  mac_address: !secret odyssey_ble
  name: Odyssey
  # Open the gate when the bluetooth signal is detected
  on_press:
  - switch.turn_on: ${id_prefix}open
  # Close the gate when the bluetooth signal is lost
  on_release:
  - switch.turn_off: ${id_prefix}open

# Detect when the M3 bluetooth is on and within range
- id: m3
  platform: ble_presence
  mac_address: !secret m3_ble
  name: M3
  # Open the gate when the bluetooth signal is detected
  on_press:
  - switch.turn_on: ${id_prefix}open
  # Close the gate when the bluetooth signal is lost
  on_release:
  - switch.turn_off: ${id_prefix}open

# Detect when the Chris's phone bluetooth is on and within range
- id: chris_phone
  platform: ble_presence
  mac_address: !secret chris_phone_ble
  name: Chris's Phone
  # Open the gate when the bluetooth signal is detected
  on_press:
  - switch.turn_on: ${id_prefix}open
  # Close the gate when the bluetooth signal is lost
  on_release:
  - switch.turn_off: ${id_prefix}open

sensor:
- id: odyssey_rssi
  platform: ble_rssi
  mac_address: !secret odyssey_ble
  internal: true

- id: m3_rssi
  platform: ble_rssi
  mac_address: !secret m3_ble
  internal: true

- id: chris_phone_rssi
  platform: ble_rssi
  mac_address: !secret chris_phone_ble
  internal: true

cover:
- id: ${id_prefix}cover
  platform: template
  name: ${label}
  lambda: |-
    if(id(${id_prefix}open).state) {
      return COVER_OPEN;
    }
    else {
      return COVER_CLOSED;
    }
  optimistic: true
  open_action:
  - switch.turn_on: ${id_prefix}open
  close_action:
  - switch.turn_off: ${id_prefix}open
