substitutions:
  name: odyssey
  id_prefix: ${name}_
  name_txt: Honda Odyssey
  device_ip: 192.168.1.88

esphome:
  name: ${name}
  platform: ESP32
  board: nodemcu-32s
  includes:
  - _BLEDevice.h
  on_boot:
    priority: -800
    then:
    - lambda: |-
            BLEDevice::setPower(ESP_PWR_LVL_P9);

<<: !include .shared.yaml

# Example configuration entry
esp32_ble_beacon:
  type: iBeacon
  uuid: !secret odyssey_uuid
